# docker build -f Dockerfile_edge -t accetto/dev-base-alpine .
# docker build -f Dockerfile_edge --build-arg BASETAG=dev -t accetto/dev-base-alpine:dev .

ARG BASETAG=edge

FROM alpine:${BASETAG}

ENV REFRESHED_AT 2018-06-19

LABEL \
    maintainer="https://github.com/accetto" \
    vendor="accetto"

### supports testing, should be overriden
ENTRYPOINT ["tail", "-f", "/dev/null"]
