# docker build -f Dockerfile_edge -t accetto/dev-base-alpine .
# docker build -f Dockerfile_edge --build-arg BASETAG=dev -t accetto/dev-base-alpine:dev .

ARG BASETAG=edge

FROM alpine:${BASETAG}

ENV REFRESHED_AT 2018-05-10

LABEL vendor="accetto" \
    maintainer="https://github.com/accetto" \
    any.accetto.description="Alpine base" \
    any.accetto.display-name="Alpine base for development" \
    any.accetto.expose-services="none" \
    any.accetto.tags="alpine, base, development"

WORKDIR /install
COPY ./src/ .
RUN sh ./tools.sh

CMD ["/bin/sh"]
