# docker build -f Dockerfile-ubuntu -t accetto/dev-base-ubuntu .
# docker build -f Dockerfile-ubuntu --build-arg BASETAG=rolling -t accetto/dev-base-ubuntu:rolling .

ARG BASETAG=latest
FROM ubuntu:${BASETAG}

ENV REFRESHED_AT 2018-05-05

LABEL vendor="accetto" \
    maintainer="https://github.com/accetto" \
    any.accetto.description="Ubuntu base" \
    any.accetto.display-name="Ubuntu base for development" \
    any.accetto.expose-services="none" \
    any.accetto.tags="ubuntu, base, development"

RUN apt-get update

CMD ["/bin/bash"]
