# docker build -f Dockerfile-ubuntu -t accetto/dev-base-ubuntu .

FROM ubuntu

ENV REFRESHED_AT 2018-04-07

LABEL vendor="accetto" \
    maintainer="https://github.com/accetto" \
    any.accetto.description="Ubuntu base" \
    any.accetto.display-name="Ubuntu base for developement" \
    any.accetto.expose-services="none" \
    any.accetto.tags="ubuntu, base, development"

RUN apt-get update

CMD ["/bin/bash"]
