# docker build -f Dockerfile_rolling -t accetto/dev-base-ubuntu.rolling .
# docker build -f Dockerfile_rolling --build-arg BASETAG=17.10 -t accetto/dev-base-ubuntu:17.10 .

ARG BASETAG=rolling

FROM ubuntu:${BASETAG}

ENV REFRESHED_AT 2019-05-01

LABEL \
    maintainer="https://github.com/accetto" \
    vendor="accetto"

### supports testing, should be overriden
ENTRYPOINT ["tail", "-f", "/dev/null"]
