# docker build -f Dockerfile_rolling -t accetto/dev-base-ubuntu.rolling .
# docker build -f Dockerfile_rolling --build-arg BASETAG=17.10 -t accetto/dev-base-ubuntu:17.10 .

ARG BASETAG=rolling

FROM ubuntu:${BASETAG}

ENV REFRESHED_AT 2018-05-10

LABEL vendor="accetto" \
    maintainer="https://github.com/accetto" \
    any.accetto.description="Ubuntu base" \
    any.accetto.display-name="Ubuntu base for development" \
    any.accetto.expose-services="none" \
    any.accetto.tags="ubuntu, base, development"

WORKDIR /install
COPY ./src/tools.sh .
RUN sh ./tools.sh

CMD ["/bin/bash"]
